---

- name: Add ES gpg key in authorized apt keys
  apt_key:
    keyserver: 'pgp.mit.edu'
    id: 'D88E42B4'
  register: aptkey

- name: Configuring upstream repository for kibana5
  apt_repository:
      repo: 'deb http://artifacts.elastic.co/packages/5.x/apt stable main'
      state: 'present'
      filename: 'elastic_5_packages'
  register: repository

- name: Update apt cache
  apt:
    update_cache: True
  when: aptkey.changed or repository.changed

- name: Installing kibana5 package
  apt:
    name: "kibana={{ kibana5_config.package.version }}"
    force: yes
    state: present
